### ISSUE TITLE
/PASSWORD setting in start.sh

### ISSUE THREAD

**Issue by vsoch** [mwaeckerlin/openldap#1]
hey @mwaeckerlin ! I am new to LDAP so please excuse my missing knowledge in advance.

I'm helping to set up a server for Singularity Registry ( we have a lot of LDAP users!) and I was able to start the image, but when I issue any command to the ldap executables, I can't seem to authenticate (even with -x). I looked back in the start up log and I see this:

```
starting slapd ...
/start.sh: line 134: /PASSWORD: No such file or directory
Administrator Password: 
```
Should this be something that is parsed from the environment variable? Or some other source? It would be fantastic to have a working example to play around with. Here is the message that I keep getting, regardless of the executable that I use:

```
root@docker[72b21bd3c290]:/# ldapadd 
SASL/DIGEST-MD5 authentication started
Please enter your authentication name: admin
Please enter your password: 
ldap_sasl_interactive_bind_s: Invalid credentials (49)
	additional info: SASL(-13): user not found: no secret in database
```

and [here is our work in progress](https://github.com/singularityhub/sregistry/pull/49) if you are interested. Thanks in advance!

**Comment by mwaeckerlin** [comment]
There is a problem, I'll fix it. Thank you.

**Comment by vsoch** [comment]
Awesome, thank you :)

**Comment by mwaeckerlin** [comment]
Please make sure, you use the latest build: `docker pull mwaeckerlin/openldap` - please wait some minutes until the new build is available on: https://hub.docker.com/r/mwaeckerlin/openldap/builds/

With the latest build, it should already have been fixed. Anyway, I improved the setup.

I tested by executing: https://marc.wäckerlin.ch/computer/setup-openldap-server-in-docker

**Comment by mwaeckerlin** [comment]
(build is now ready)

**Comment by vsoch** [comment]
Works great, thank you!

And super badass webpage, haha.

**Comment by vsoch** [comment]
Thank you again for this! We were able to test and add an example of using your container for LDAP with Singularity Registry --> https://singularityhub.github.io/sregistry/plugins/ldap.html woohoo!
