### ISSUE TITLE
admin user can't modify the config?

### ISSUE THREAD

**Issue by goeland86** [mwaeckerlin/openldap#2]
Hello,

I found your LDAP image one of the easier ones to get going with, but I'm stumbling head first into something I'm not sure how to solve. I'm only beginning to understand LDAP, and there are several concepts I haven't fully grasped yet either, so my apologies if this is something simple, but Google has eluded my quest for answers.

My admin user is cn=admin,dc=example,dc=com, with a tested password.
I've managed to import our users from the Synology LDAP's export LDIF (exported using Apache Directory Studio), and have them setup neatly in groups.

I noticed I couldn't enable the memberOf attributes on the users because the attribute is missing in the schema. Reading up a bit, I found this explanation of how to enable the memberOf attribute: https://www.adimian.com/blog/2014/10/how-to-enable-memberof-using-openldap/

However I get an error when I try to execute the following LDIF to enable the module:
```dn: cn=module,cn=config
cn: module
objectClass: olcModuleList
olcModuleLoad: memberof
olcModulePath: /usr/lib/ldap
```
The error is as follows:
```
root@docker[0dc04192136f]:~# ldapadd -x -w `cat password` -h localhost -D cn=admin,dc=example,dc=com -a
dn: cn=module,cn=config
cn: module
objectClass: olcModuleList
olcModuleLoad: memberof
olcModulePath: /usr/lib/ldap

adding new entry "cn=module,cn=config"
ldap_add: Insufficient access (50)
```

Notice I ran this from within the container, so perhaps I'm missing something crucial in the documentation about how to modify the existing schema?

Any help is much appreciated to resolve this issue.

**Comment by mwaeckerlin** [comment]
Have a look in my scripts, i.e. start.sh → You don't need a password for 
local manipulation on the command line.

Am 13.12.2017 17:43, schrieb Jon C:
> Hello,
> 
> I found your LDAP image one of the easier ones to get going with, but
> I'm stumbling head first into something I'm not sure how to solve. I'm
> only beginning to understand LDAP, and there are several concepts I
> haven't fully grasped yet either, so my apologies if this is something
> simple, but Google has eluded my quest for answers.
> 
> My admin user is cn=admin,dc=example,dc=com, with a tested password.
> I've managed to import our users from the Synology LDAP's export LDIF
> (exported using Apache Directory Studio), and have them setup neatly
> in groups.
> 
> I noticed I couldn't enable the memberOf attributes on the users
> because the attribute is missing in the schema. Reading up a bit, I
> found this explanation of how to enable the memberOf attribute:
> https://www.adimian.com/blog/2014/10/how-to-enable-memberof-using-openldap/
> 
> However I get an error when I try to execute the following LDIF to
> enable the module:
> ```dn: cn=module,cn=config
> cn: module
> objectClass: olcModuleList
> olcModuleLoad: memberof
> olcModulePath: /usr/lib/ldap
> ```
> The error is as follows:
> ```
> root@docker[0dc04192136f]:~# ldapadd -x -w `cat password` -h localhost
> -D cn=admin,dc=gamaya,dc=com -a
> dn: cn=module,cn=config
> cn: module
> objectClass: olcModuleList
> olcModuleLoad: memberof
> olcModulePath: /usr/lib/ldap
> 
> adding new entry "cn=module,cn=config"
> ldap_add: Insufficient access (50)
> ```
> 
> Notice I ran this from within the container, so perhaps I'm missing
> something crucial in the documentation about how to modify the
> existing schema?
> 
> Any help is much appreciated to resolve this issue.

-- 
Marc Wäckerlin
marc@waeckerlin.org
https://marc.wäckerlin.ch

**Comment by goeland86** [comment]
Thanks, that helped a lot.
