### ISSUE TITLE
back_mdb fails to load

### ISSUE THREAD

**Issue by dnknth** [mwaeckerlin/openldap#23]
Hello @mwaeckerlin,

Since the last image update, the container fails to start from scratch. There is an error when loading the initial LDIF.
I added a `-v` to line 91 of `start.sh`, and the problem seems to be:

```text
ldap_1     | + test -e /var/restore/test-data.ldif
ldap_1     | + rm -f '/var/lib/ldap/*'
ldap_1     | + slapadd -v -f /etc/ldap/slapd.conf -l /var/restore/test-data.ldif
ldap_1     | lt_dlopenext failed: (back_mdb.la) file not found
ldap_1     | /etc/ldap/slapd.conf: line 18: <moduleload> handler exited with 1!
```

Any idea what might be going wrong?

**Comment by dnknth** [comment]
#24 fixes this. Apparently, there were two `moduleload back_mdb.la` lines in `/etc/ldap/slapd.conf`, one commented out and the other one uncommented.

**Comment by Serviceplatformen** [comment]
Is there a new latest version that includes a fix ?
