### ISSUE TITLE
Add ACL

### ISSUE THREAD

**Issue by HamburgerJungeJr** [mwaeckerlin/openldap#6]
How do I add a new ACL to the LDAP-Server?

I tried to connect to the cn=config tree but Ion get the response "No such Object".
Also I tried to add the ACL to the slapd.conf file but the changes are deleted when I restart the container.

**Comment by mwaeckerlin** [comment]
Could you please copy your `slapd.conf` file with ACL configurations?

I migrated from Ubuntu to Alpine Linux as base image, because it saves a lot of space. But in Alpine, OpenLDAP is not based on `cn=config`, but on `slapd.conf`.

Yes: `slapd.conf`is (re-) generated on container startup. To solve your problem, I could add ACL as optional feature (e.g. `-e ACL=1`).

**Comment by smacz42** [comment]
How would the ACLs be specified?

For instance, if I would want to add:

```
access to *
  by self write
  by users read
  by anonymous auth
```

Would I put something in the dockerfile like:

```
ACL: |-
  access to *
    by self write
    by users read
    by anonymous auth
```
(Or however multiline would work)

Would there be any sane defaults if ACL is specified? Or would the choice be to either use the default (if no access controls are present, the default policy allows anyone and everyone to read anything but restricts updates to rootdn. e.g., "access to * by * read") or define their own ACLs?

**Comment by smacz42** [comment]
Actually, I was trolling through `start.sh`, and found the following code in [lines 39-41](https://github.com/mwaeckerlin/openldap/blob/master/start.sh#L39-#L41):

```
echo "$ACCESS_RULES" | sed 's, access to,\
access to,g;s, by,\
\tby,g' >> /etc/ldap/slapd.conf
```

This looked to have been added in https://github.com/mwaeckerlin/openldap/commit/40ba42017e15cdc056fc6259d67a1054a3502ca0. Can we call this issue Closed then? I am now able to create a custom ACL with the following variable:

```
-e ACCESS_RULES=' access to dn.base="" by * read access to dn.base="cn=Subschema" by * read access to * by self write by users read by anonymous auth'
```

**Comment by mwaeckerlin** [comment]
I could add something similar to #8 and #10 for ACL. Would that be a solution?

**Comment by smacz42** [comment]
The functionality is already there, and can be used how I mentioned above. This issue should probably be closed.
