### ISSUE TITLE
Cannot add indexes

### ISSUE THREAD

**Issue by smacz42** [mwaeckerlin/openldap#8]
I'm running into this issue when having a user change their own password:

```
5d16e3d2 <= mdb_equality_candidates: (uid) not indexed
```

Which seems to indicate that the uid (which is the objectclass that it's searching for) is not indexed. Sure enough, when I look in the slapd.conf file, the only index is for objectClass.

Would there be a way to specify indexes to add? I would imaging it could be something like how ACLs are implemented (see https://github.com/mwaeckerlin/openldap/issues/6#issuecomment-506924146)

**Comment by mwaeckerlin** [comment]
@smacz42, can I close this issue as done, according to #10?

**Comment by smacz42** [comment]
Yep, that PR allows the ability to specify indexes. Closing this issue.
